In [2]:
import scphylo as scp

# sphinx_gallery_thumbnail_path = "_static/thumbnails/clonal.png"

In [3]:
grnd = scp.io.read("Demo_out.CFMatrix")
sol = scp.io.read("Demo_reconstructed.CFMatrix")

In [6]:
grnd

,mut0,mut1,mut2,mut3,mut4,mut5,mut6,mut7,mut8,mut9,...,mut90,mut91,mut92,mut93,mut94,mut95,mut96,mut97,mut98,mut99
cellIDxmutID,,,,,,,,,,,,,,,,,,,,,
cell0,1,1,0,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
cell1,0,0,0,0,0,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
cell2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
cell3,1,1,1,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
cell4,0,0,0,0,0,0,0,1,1,1,...,0,1,1,1,1,1,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
cell95,1,1,1,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
cell96,0,0,0,0,0,0,0,1,1,1,...,0,1,1,1,0,0,0,1,0,1
cell97,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
cell98,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
cell99,0,0,0,0,0,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0

In [7]:
sol

,mut0,mut1,mut2,mut3,mut4,mut5,mut6,mut7,mut8,mut9,...,mut90,mut91,mut92,mut93,mut94,mut95,mut96,mut97,mut98,mut99
cellIDxmutID,,,,,,,,,,,,,,,,,,,,,
cell0,1,1,0,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
cell1,0,0,0,0,0,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
cell2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
cell3,1,1,1,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
cell4,0,0,0,0,0,0,0,1,1,1,...,0,1,1,1,1,1,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
cell95,1,1,1,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
cell96,0,0,0,0,0,0,0,1,1,1,...,0,1,1,1,0,0,0,1,0,1
cell97,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
cell98,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
cell99,0,0,0,0,0,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0

In [10]:
#https://scphylo-tools.readthedocs.io/en/latest/auto_examples/comparison/compute_ad.html
#Calculating the ancestor-descendent accuracy.
scp.tl.ad(grnd, sol)

1.0

In [9]:
#Calculating the commonly ancestor sets score (CASet).

scp.tl.caset(grnd, sol)

1.0